---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.appName }}
  namespace: "{{ .Values.namespace }}"
  annotations:
    # default is leastconn which tends to route all traffic to the same pods.
    haproxy.router.openshift.io/balance: "roundrobin"
    # Disable the cookies for load testing as the load test is coming from a single source host.
    haproxy.router.openshift.io/disable_cookies: "true"
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.wordpress.whitelistedIPs }}
spec:
  host: {{ .Values.domain }}
  port:
    targetPort: {{ .Values.wordpress.service.targetPort }}
  tls:
    key: |-
{{ .Files.Get "certs/private.key" | indent 6 }}
    certificate: |-
{{ .Files.Get "certs/certificate.crt" | indent 6 }}
    caCertificate: |-
{{ .Files.Get "certs/cacertificate.crt" | indent 6 }}
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.appName }}
    weight: 100
  wildcardPolicy: None
...