kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-fastcgi-cache
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
