services:
  mariadb:
    image: bitnami/mariadb:11.4.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_MASTER_HOST: "%"      # TODO: This is a temp solution for local dev
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: password

  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    build:
      context: .
    ports:
      - 8080:8080
    restart: always
    environment:
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: mysite_
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: password

      PHP_FPM_ERROR_LOG: "/dev/stderr"
      PHP_FPM_LOG_LEVEL: "debug"  # or "notice", "warning", "error"
      PHP_ERROR_LOG: "/dev/stderr"
      PHP_LOG_ERRORS: "1"
      PHP_DISPLAY_ERRORS: "1"

      # Note the double $ in the variables which is needed to pass a single $ into the wp-config.php
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT: |
        define( 'WP_DEBUG_LOG', '/dev/stdout' );
        /** Enable W3 Total Cache */
        define('WP_CACHE', true); // Added by W3 Total Cache

        /* define('FORCE_SSL_ADMIN', true); */
        if($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'){
          $$_SERVER['HTTPS'] = 'on';
          $$_SERVER['SERVER_PORT'] = 443;
        }
        /* S3 Uploads */
        define('S3_UPLOADS_REGION', getenv('OS_REGION'));
        define('S3_UPLOADS_BUCKET', getenv('OS_BUCKET'));
        define('S3_UPLOADS_KEY', getenv('OS_ACCESS_KEY_ID'));
        define('S3_UPLOADS_SECRET', getenv('OS_ACCESS_SECRET'));
    volumes:
      - /mnt/wordpress-fastcgi-cache