namespace: abc123-dev
appName: my-wordpress
imageNamespace: abc123-tools
serviceAccountName: abc123-vault
domain: dev.mydomain.com


wordpress:
  # WP Config
  user: wordpress
  password: password
  adminUID: admin
  adminPassword: password
  whitelistedIPs: "*"

  deploymentAnnotations: |
    image.openshift.io/triggers: '[{
      "from": {
        "kind": "ImageStreamTag",
        "namespace": "{{ .Values.imageNamespace }}",
        "name": "{{ .Values.appName }}"
      },
      "fieldPath": "spec.template.spec.containers[0].image"
    }]'


  # infrastructure
  replicaCount: 1
  imageRegistry: image-registry.openshift-image-registry.svc:5000
  imageNamespace: abc123-tools
  imageVersion: dev
  service:
    port: 80
    targetPort: 8080
  resources:
    limits:
      cpu: 100m
      memory: "256Mi"
    requests:
      cpu: 100m
      memory: "128Mi"

  hpa:
    minReplicas: 1
    maxReplicas: 3
    averageCpuUtilization: 80

  php:
    debug:
      enabled: false  # default to disabled
