apiVersion: v2
name: galera-helm
description: A customized version of mariadb-galera for OCP
type: application
version: 0.1.0
appVersion: "1.17.0"

dependencies:
  - name: mariadb-galera
    version: 14.0.10
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
