licensePlate: abc123
nameSpaceSuffix: test
subdomain: test
appName: galera
cluster: gold
clusterAddress: "gcomm://{{ .Release.Name }}-mariadb-galera-0.{{ .Release.Name }}-mariadb-galera-headless.{{ .Values.licensePlate }}-{{ .Values.nameSpaceSuffix }}.svc.cluster.local,{{ .Release.Name }}-mariadb-galera-1.{{ .Release.Name }}-mariadb-galera-headless.{{ .Values.licensePlate }}-{{ .Values.nameSpaceSuffix }}.svc.cluster.local,{{ .Release.Name }}-mariadb-galera-2.{{ .Release.Name }}-mariadb-galera-headless.{{ .Values.licensePlate }}-{{ .Values.nameSpaceSuffix }}.svc.cluster.local"

mariadb-galera:
  image:
    debug: true

  services:
    ports:
      mysql: 3306
      sst: 4444
      ist: 4568
      gcomm: 4567
    nodePorts:
      nodePorts:
      mysql: ""
      sst: ""
      ist: ""
      gcomm: ""

  rootUser:
    user: root
    password: "password"

  db:
    user: "wordpress"
    password: "password"
    name: wordpress

  galera:
    bootstrap:
      forceSafeToBootstrap: true

  mariabackup:
    user: mariabackup
    password: "password"

  mariadbConfiguration:
    tmp_table_size=8M
    max_heap_table_size=8M
    query_cache_type=0
    query_cache_limit=4M
    query_cache_size=0
    innodb_log_file_size=8M
    innodb_buffer_pool_size=512Mi
    wsrep_provider_options="gcache.size=16M"

  persistence:
    size: 100Mi

  resourcesPreset: "none"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 300Mi

  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

  metrics:
    extraFlags:
      - "--log-error-verbosity=3"
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 300Mi
