name: Release Galera Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - galera-helm/**
      - .github/workflows/package_galera-helm_chart.yaml

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Package Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Chart Version
        id: chart-version
        run: |
          CHART_VERSION=$(awk '/^version:/ {print $2}' galera-helm/Chart.yaml)
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Package Helm Chart
        run: |
          helm package galera-helm/
          helm repo index . --url https://bashbang.github.io/ocp-galera/ --merge index.yaml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.chart-version.outputs.version }}
          files: |
            *.tgz
          generate_release_notes: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ocp-galera
          publish_branch: gh-pages
