name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - wp-helm/**
      - galera-helm/**
      - .github/workflows/package_helm_charts.yaml

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Package Helm Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Changes
        id: changes
        run: |
          # Check for changes in wp-helm
          if git diff --name-only HEAD^ HEAD | grep -q "^wp-helm/"; then
            echo "wp_helm_changed=true" >> $GITHUB_OUTPUT
          else
            echo "wp_helm_changed=false" >> $GITHUB_OUTPUT
          fi

          # Check for changes in galera-helm
          if git diff --name-only HEAD^ HEAD | grep -q "^galera-helm/"; then
            echo "galera_helm_changed=true" >> $GITHUB_OUTPUT
          else
            echo "galera_helm_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Package WP Helm Chart
        if: ${{ steps.changes.outputs.wp_helm_changed == 'true' }}
        working-directory: ./wp-helm
        run: |
          mkdir -p ../output
          helm package . -d ../output

      - name: Package Galera Helm Chart
        if: ${{ steps.changes.outputs.galera_helm_changed == 'true' }}
        working-directory: ./galera-helm
        run: |
          mkdir -p ../output
          helm package . -d ../output

      - name: Update Helm Repo Index
        if: ${{ steps.changes.outputs.wp_helm_changed == 'true' || steps.changes.outputs.galera_helm_changed == 'true' }}
        working-directory: ./output
        run: |
          helm repo index . --url https://bashbang.github.io/ocp-wordpress/ --merge ../index.yaml

      - name: Deploy to GitHub Pages
        if: ${{ steps.changes.outputs.wp_helm_changed == 'true' || steps
